export default {
  "__comp---theme-doc-item-178-a40": [() => import(/* webpackChunkName: "__comp---theme-doc-item-178-a40" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "__comp---theme-doc-roota-94-67a": [() => import(/* webpackChunkName: "__comp---theme-doc-roota-94-67a" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "__comp---theme-doc-version-roota-7-b-5de": [() => import(/* webpackChunkName: "__comp---theme-doc-version-roota-7-b-5de" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "__comp---theme-docs-root-5-e-9-0b6": [() => import(/* webpackChunkName: "__comp---theme-docs-root-5-e-9-0b6" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "content---a-09-df0": [() => import(/* webpackChunkName: "content---a-09-df0" */ "@site/docs/introduction.md"), "@site/docs/introduction.md", require.resolveWeak("@site/docs/introduction.md")],
  "content---api-channel-46-d-389": [() => import(/* webpackChunkName: "content---api-channel-46-d-389" */ "@site/docs/api/channel.md"), "@site/docs/api/channel.md", require.resolveWeak("@site/docs/api/channel.md")],
  "content---api-message-93-d-31e": [() => import(/* webpackChunkName: "content---api-message-93-d-31e" */ "@site/docs/api/message.md"), "@site/docs/api/message.md", require.resolveWeak("@site/docs/api/message.md")],
  "content---api-overview-65-d-4dc": [() => import(/* webpackChunkName: "content---api-overview-65-d-4dc" */ "@site/docs/api/overview.md"), "@site/docs/api/overview.md", require.resolveWeak("@site/docs/api/overview.md")],
  "content---api-user-778-b1f": [() => import(/* webpackChunkName: "content---api-user-778-b1f" */ "@site/docs/api/user.md"), "@site/docs/api/user.md", require.resolveWeak("@site/docs/api/user.md")],
  "plugin---24-e-617": [() => import(/* webpackChunkName: "plugin---24-e-617" */ "/Users/oledonnermeyer/Documents/coding/oneshot/oneshot_doc/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json"), "/Users/oledonnermeyer/Documents/coding/oneshot/oneshot_doc/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json", require.resolveWeak("/Users/oledonnermeyer/Documents/coding/oneshot/oneshot_doc/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json")],
  "version---935-fcf": [() => import(/* webpackChunkName: "version---935-fcf" */ "~docs/default/version-current-metadata-prop-751.json"), "~docs/default/version-current-metadata-prop-751.json", require.resolveWeak("~docs/default/version-current-metadata-prop-751.json")],};
